name: Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: xcodebuild -scheme 'ViewFactory' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' build

  test:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout project repo
      uses: actions/checkout@v2

    - name: Test
      shell: bash
      run: xcodebuild -scheme 'ViewFactory' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' test
